channels:
    - conda-forge
    - schrodinger
dependencies:
    - fresnel
    - povray
    - pyglet
    - pip
    - pip:
      - matplotlib
      - nbsphinx
      - pythreejs
      - pyvirtualdisplay
      - vispy
