# specify dependencies for mybinder.org operation (see also apt.txt
# for the full set)
channels:
    - conda-forge
dependencies:
    - cython
    - fresnel
    - pip
    - pip:
      - matplotlib
      - pythreejs
      - git+https://github.com/vispy/vispy
      - ..
